### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by dmytro-dubovets** [dmytro-dubovets/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by YuliaAwesome** [comment]
Facebook - https://www.facebook.com/POTUS/
Twitter - https://twitter.com/realdonaldtrump
Instagram - https://www.instagram.com/realDonaldTrump/
